### PR TITLE
feat(server): support cmd generate-sharelink

### PR DESCRIPTION
**Pull request by mzz2017**
### Background

For example:

```bash
> ./juicity-server generate-sharinglink -c /etc/juicity/server.json
juicity://00000000-0000-0000-0000-000000000000:mypassword@1.2.3.4:15333?congestion_control=bbr&pinned_certchain_sha256=5ykL73pOK7NAu92A48dCrFjDqDowdChUSmlpQzudmvc%3D&sni=download.microsoft.com
```

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/juicity/juicity

### Full changelogs

- feat(server): support cmd generate-sharinglink

### Issue reference

Closes #_[issue number]_

### CODE REVIEW

**Review by kunish — APPROVED** [review]
Good stuff

**Comment by yqlbu** [comment]
Shall we add some lines in README?

**Comment by mzz2017** [comment]
Maybe time and dnsnames need to be veirified.

**Review by yqlbu — APPROVED** [review]

**Comment by kunish** [comment]
Tested on 10 different machines. Generated and imported into daed with those links, confirmed to be working as expected.

**Review by kunish — APPROVED** [review]

**Comment by yqlbu** [comment]
@kunish Cool 🤙

**Pull request merged**
